version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fastifyApi
    volumes:
      - fastify_pg_data:/bitnami/postgresql

  redis-fastify:
    image: bitnami/redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=redisdocker
      - REDIS_PORT_NUMBER=6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend-fastify:
    build: .
    command: npm run dev
    depends_on:
      - postgres
      - redis-fastify
    ports:
      - "3333:3333"
    volumes:
      - .:/backend-fastify
volumes:
  fastify_pg_data:
  redis_data:
